---
# For configuration options and examples, please see:
# https://gethomepage.dev/configuration/services

- Infrastructure:
    - Proxmox:
        href: https://proxmox.home.stefancyliax.de
        icon: proxmox
        description: Virtualization Hypervisor
        widget:
          type: proxmox
          url: https://10.1.23.4:8006
          username: "root@pam!homepage"
          password: "{{HOMEPAGE_VAR_PROXMOX_TOKEN_SECRET}}"
    - Unraid:
        href: http://10.1.23.5
        icon: unraid
        description: Storage NAS
    - Dockhand:
        href: https://dockhand.home.stefancyliax.de
        icon: docker
        description: Deployment Orchestrator
    - ntfy:
        href: https://ntfy.home.stefancyliax.de
        icon: ntfy
        description: Notification Server
    - ZeroByte:
        href: http://10.1.23.224:4096
        icon: network
        description: Secure Backup Framework

- Smart Home:
    - Home Assistant:
        href: http://10.1.23.5:8123
        icon: home-assistant
        description: Home Automation Hub
    - ESPHome:
        href: http://10.1.107.8:6052
        icon: esphome
        description: Microcontroller Firmware Management


- Applications:
    - Open-WebUI:
        href: http://10.1.23.224:3000
        icon: open-webui
        description: LLM Chat Interface
    - n8n:
        href: http://10.1.23.224:5678
        icon: n8n
        description: Workflow Automation
    - NocoDB:
        href: http://10.1.23.224:8080
        icon: nocodb
        description: Database Platform
    - Paperless-ngx:
        href: https://paperless.home.stefancyliax.de
        icon: paperless-ngx
        description: Document Management
    - Paperless-AI:
        href: http://10.1.23.224:8001
        icon: paperless-ngx
        description: AI Document Classifier
    - Paperless-GPT:
        href: http://10.1.23.224:8002
        icon: paperless-ngx
        description: Document LLM Assistant
    - Grimmory:
        href: https://grimmory.home.stefancyliax.de/
        icon: booklore
        description: Digital Library Manager
    - NextExplorer:
        href: http://10.1.23.224:3001
        icon: files
        description: File Explorer
    - Kestra:
        href: http://10.1.23.224:8082
        icon: kestra
        description: Workflow Orchestration
    - Stirling PDF:
        href: http://10.1.23.224:8084
        icon: pdf
        description: PDF Manipulation Tools
    - Grimoire:
        href: https://grimoire.home.stefancyliax.de
        icon: bookmark
        description: Bookmark Manager

- AI & ML:
    - Ollama:
        href: http://10.1.23.17:11434
        icon: ollama
        description: LLM Inference Server
    - Speaches:
        href: http://10.1.23.224:8003
        icon: whisper
        description: Speech-to-Text API

- Monitoring:
    - Grafana old:
        href: http://10.1.23.5:3000
        icon: grafana
        description: Metrics & Visualization
    - Grafana:
        href: http://10.1.23.184:3001
        icon: grafana
        description: Metrics & Visualization
    - Prometheus:
        href: http://10.1.23.184:9090
        icon: prometheus
        description: Time-series Metrics
    - InfluxDB:
        href: http://10.1.23.184:8086
        icon: influxdb
        description: Long-term Database

- Fallback:
    - Proxmox:
        href: https://10.1.23.4:8006
        icon: proxmox
        description: Virtualization Hypervisor
    - Unraid:
        href: http://10.1.23.5
        icon: unraid
        description: Storage NAS
    - Dockhand:
        href: http://10.1.23.184:3000
        icon: docker
        description: Deployment Orchestrator