theme: auto
default_2fa_method: totp

server:
  address: "tcp://0.0.0.0:9091"

log:
  level: info

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: one_factor
  rules:
    - domain: "*.home.stefancyliax.de"
      policy: one_factor

session:
  name: authelia_session
  secret: '{{ secret "/config/secrets/session_secret" | trim }}'
  cookies:
    - domain: "stefancyliax.de"
      authelia_url: "https://auth.home.stefancyliax.de"

storage:
  encryption_key: '{{ secret "/config/secrets/storage_key" | trim }}'
  local:
    path: /config/db.sqlite3

identity_validation:
  reset_password:
    jwt_secret: '{{ secret "/config/secrets/jwt_secret" | trim }}'

notifier:
  filesystem:
    filename: /config/notification.txt

identity_providers:
  oidc:
    hmac_secret: '{{ secret "/config/secrets/oidc_hmac" | trim }}'
    jwks:
      - key_id: main
        algorithm: RS256
        use: sig
        key: {{ secret "/config/secrets/oidc_rsa.pem" | mindent 10 "|" | msquote }}
    clients:
      - client_id: grimmory
        client_name: Grimmory
        client_secret: '$pbkdf2-sha512$310000$9.wQl3nXxoQLzP8IcpMiSA$fiS5wjDeI.6E2KbjW9aCAhLGjl6gwpVi1iDe0iO1GE8.6DHBhX11rnzifWmzV1EGdbWkosxO2WscfYVj.Z49Hg'
        public: false
        token_endpoint_auth_method: client_secret_post
        authorization_policy: one_factor
        require_pkce: true
        pkce_challenge_method: S256
        response_types:
          - code
        scopes:
          - openid
          - profile
          - email
          - groups
          - offline_access
        redirect_uris:
          - https://grimmory.home.stefancyliax.de/oauth2-callback

      - client_id: proxmox
        client_name: Proxmox VE
        client_secret: '$pbkdf2-sha512$310000$hXdBhS6tujkUA2L0j9l.xA$kA1mN2wwrXJuV85DBhjaizh0VO6tNeWqaEY7nc219E9qXCYL5RwxyJv8SbRyWXvGUmoBBc/dCL3CgFLGqTX8eg'
        public: false
        token_endpoint_auth_method: client_secret_basic
        authorization_policy: one_factor
        require_pkce: false
        response_types:
          - code
        scopes:
          - openid
          - profile
          - email
          - groups
        redirect_uris:
          - https://proxmox.home.stefancyliax.de

      - client_id: dockhand
        client_name: Dockhand
        client_secret: '$pbkdf2-sha512$310000$nSLI0gVpaPW.cVzpceqprQ$5BjFHJW8N6Wn.mG6OKKbzy4cpJqkXBYvJVXiAko.GaaKKn6.IurMVPF/uBEZXDDLws4A8ZG/mudUn1amIFSfzg'
        public: false
        token_endpoint_auth_method: client_secret_post
        authorization_policy: one_factor
        require_pkce: true
        pkce_challenge_method: S256
        response_types:
          - code
        scopes:
          - openid
          - profile
          - email
          - groups
        redirect_uris:
          - https://dockhand.home.stefancyliax.de/api/auth/oidc/callback
