theme: auto
default_2fa_method: totp

server:
  address: "tcp://0.0.0.0:9091"

log:
  level: info

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: two_factor
  rules:
    - domain: "*.home.stefancyliax.de"
      policy: two_factor

session:
  name: authelia_session
  secret: unsecure_session_secret # WARNING: Change this in production
  cookies:
    - domain: "stefancyliax.de"
      authelia_url: "https://auth.home.stefancyliax.de"

storage:
  encryption_key: "unsecure_encryption_key_change_in_production" # MUST BE >20 CHARS
  local:
    path: /config/db.sqlite3

identity_validation:
  reset_password:
    jwt_secret: "unsecure_jwt_secret_change_in_production"

notifier:
  filesystem:
    filename: /config/notification.txt
