# Docker Compose file for running paperless from the docker container registry.

services:
  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
      - redisdata:/data
  db:
    image: docker.io/library/postgres:18
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8008:8000"
    volumes:
      - /mnt/data/paperless/data:/usr/src/paperless/data
      - /mnt/data/paperless/media:/usr/src/paperless/media
      - /mnt/data/paperless/export:/usr/src/paperless/export
      - /home/stefan/paperless-consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_CONSUMER_IGNORE_PATTERN: ".*DS_Store"
      USERMAP_UID: 1000
      USERMAP_GID: 100

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.25
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped

  # paperless-ai:
  #   image: clusterzx/paperless-ai:latest
  #   container_name: paperless-ai
  #   restart: unless-stopped
  #   environment:
  #     PUID: 1000
  #     PGID: 1000
  #     RAG_SERVICE_URL: http://paperless-ngx:8008
  #     RAG_SERVICE_ENABLED: true
  #   ports:
  #     - "8001:3000"
  #   volumes:
  #     - paperless-ai_data:/app/data
  #   depends_on:
  #     - paperless-ngx

  paperless-gpt:
    image: icereed/paperless-gpt:latest
    container_name: paperless-gpt
    restart: unless-stopped
    environment:
      PAPERLESS_BASE_URL: "http://paperless-ngx:8000"
      PAPERLESS_API_TOKEN: ${PAPERLESS_API_TOKEN}
      LLM_PROVIDER: "openai"
      LLM_MODEL: "gemma4"
      OPENAI_BASE_URL: "http://100.90.253.20:8080/v1"
      OPENAI_API_KEY: "sk-dummy-key"
      LLM_LANGUAGE: "German"
      OCR_PROVIDER: "llm"
      VISION_LLM_PROVIDER: "openai"
      VISION_LLM_MODEL: "glm-ocr"
      MANUAL_TAG: "#manual-tag"
      AUTO_TAG: "#auto-process"
      AUTO_OCR_TAG: "#auto-ocr"
      PDF_OCR_TAGGING: true
      PDF_OCR_COMPLETE_TAG: "#gpt-processed"
      TOKEN_LIMIT: "32000"
      OCR_LIMIT_PAGES: 12


    ports:
      - "8002:8080"
    depends_on:
      - paperless-ngx

volumes:
  data:
  media:
  pgdata:
  redisdata:
  paperless-ai_data: