apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: Prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: homelab
      defaultBucket: homelab
    secureJsonData:
      token: ${INFLUXDB_ADMIN_TOKEN}
    editable: false
