name: NixOS Apply

on:
  push:
    branches: [ main ]
    # paths:
    #   - 'NixOS/**'
  workflow_dispatch: # Allows manual triggering

jobs:
  nixos:
    runs-on: [ self-hosted, nixos ]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Deploy with Colmena
        # This step is crucial for Colmena to be able to push to the VM.
        # You'll need to add your SSH private key to GitHub Secrets.
        run: |
          whoami
          ls -la
          ls -la NixOS
          cat NixOS/hive.nix

          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_DEPLOY_KEY }}" | ssh-add -
          
          colmena eval NixOS/hive.nix
