name: NixOS Apply

on:
  push:
    branches: [ main ]
    # paths:
    #   - 'NixOS/**'
  workflow_dispatch: # Allows manual triggering

jobs:
  nixos:
    runs-on: [ self-hosted, nixos ]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Deploy with Colmenao
        working-directory: ./NixOS
        run: |
          whoami
          ls -la

          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_DEPLOY_KEY }}" | ssh-add -
                    
          # colmena build
          colmena apply -f flake.nix
