name: Test Self-Hosted Runner

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: [ self-hosted, infra ]
    steps:
      - name: Who am I?
        run: |
          whoami
          hostname
          ip addr show eth0
